(() => {
  const events = [
    {day:'28', month:'AUG', category:'Hackathon', title:'Build for Campus', time:'9:30 AM – 7:00 PM', place:'Seminar Hall', detail:'Turn a real student problem into a working idea with your team.', color:'lime'},
    {day:'30', month:'AUG', category:'Workshop', title:'Git & GitHub, beyond basics', time:'2:00 PM – 4:30 PM', place:'Lab 204', detail:'A practical workshop on clean collaboration and better project workflows.', color:'violet'},
    {day:'02', month:'SEP', category:'Community', title:'Open-source introduction circle', time:'4:30 PM – 6:00 PM', place:'Library discussion area', detail:'Meet students building in public and find a friendly first contribution.', color:'mint'},
    {day:'06', month:'SEP', category:'Workshop', title:'Designing interfaces that work', time:'11:00 AM – 1:00 PM', place:'Innovation space', detail:'Learn the product thinking behind simple, useful student-facing UI.', color:'peach'},
    {day:'12', month:'SEP', category:'Hackathon', title:'AI Build Night', time:'5:00 PM – 9:00 PM', place:'TBA', detail:'Bring an idea, meet collaborators, and make a focused prototype.', color:'lime'}
  ];
  const grid = document.querySelector('[data-events-grid]'); const empty = document.querySelector('[data-events-empty]'); const count = document.querySelector('[data-event-count]'); const search = document.querySelector('[data-event-search]'); let category = 'all';
  const render = () => { const keyword = search.value.toLowerCase(); const list = events.filter((event) => (category === 'all' || event.category === category) && Object.values(event).join(' ').toLowerCase().includes(keyword)); count.textContent = list.length; grid.hidden = !list.length; empty.hidden = Boolean(list.length); grid.innerHTML = list.map((event) => `<article class="event-list-card"><div class="event-calendar ${event.color}"><strong>${event.day}</strong><span>${event.month}</span></div><div class="event-content"><span class="event-category">${event.category}</span><h2>${event.title}</h2><p>${event.detail}</p><div><span>◷ ${event.time}</span><span>⌖ ${event.place}</span></div></div><button aria-label="View ${event.title}">→</button></article>`).join(''); };
  document.querySelectorAll('[data-category]').forEach((button) => button.addEventListener('click', () => { category = button.dataset.category; document.querySelectorAll('[data-category]').forEach((item) => item.classList.toggle('active', item === button)); render(); })); search.addEventListener('input', render); document.querySelector('[data-clear-events]').addEventListener('click', () => { category='all'; search.value=''; document.querySelectorAll('[data-category]').forEach((item) => item.classList.toggle('active', item.dataset.category === 'all')); render(); }); render();
})();
