(() => {
  const opportunities = [
    {type:'Internship', title:'Frontend internship program', organisation:'Launchpad Studio', mode:'Remote', deadline:'6 days left', days:6, saved:84, accent:'violet', added:3},
    {type:'Hackathon', title:'National student innovation challenge', organisation:'Open Build Collective', mode:'Hybrid', deadline:'9 days left', days:9, saved:126, accent:'lime', added:1},
    {type:'Scholarship', title:'Future technologists scholarship', organisation:'Student Futures Fund', mode:'Online', deadline:'13 days left', days:13, saved:67, accent:'mint', added:5},
    {type:'Competition', title:'Design for impact challenge', organisation:'Campus Creators', mode:'Pune', deadline:'18 days left', days:18, saved:44, accent:'peach', added:2},
    {type:'Internship', title:'Open-source contributor cohort', organisation:'Community Forge', mode:'Remote', deadline:'22 days left', days:22, saved:93, accent:'mint', added:4},
    {type:'Hackathon', title:'Sustainability build weekend', organisation:'Green Tech Network', mode:'Pune', deadline:'28 days left', days:28, saved:52, accent:'lime', added:6}
  ];
  const grid = document.querySelector('[data-opportunities-grid]'); const empty = document.querySelector('[data-opportunities-empty]'); const count = document.querySelector('[data-opportunity-count]'); const search = document.querySelector('[data-opportunity-search]'); const sort = document.querySelector('[data-deadline-sort]'); let type = 'all';
  const render = () => { const keyword = search.value.trim().toLowerCase(); const list = opportunities.filter((item) => (type === 'all' || item.type === type) && Object.values(item).join(' ').toLowerCase().includes(keyword)).sort((a,b) => sort.value === 'soon' ? a.days-b.days : a.added-b.added); count.textContent = list.length; grid.hidden = !list.length; empty.hidden = Boolean(list.length); grid.innerHTML = list.map((item) => `<article class="opportunity-tile"><div class="tile-top"><span class="opportunity-tag ${item.accent}">${item.type}</span><button type="button" aria-label="Save ${item.title}">♡</button></div><div><p class="tile-organisation">${item.organisation}</p><h2>${item.title}</h2><p class="tile-mode">⌖ ${item.mode}</p></div><div class="tile-bottom"><span class="deadline">${item.deadline}</span><span>♡ ${item.saved}</span></div></article>`).join(''); };
  document.querySelectorAll('[data-opportunity-type]').forEach((button) => button.addEventListener('click', () => { type = button.dataset.opportunityType; document.querySelectorAll('[data-opportunity-type]').forEach((item) => item.classList.toggle('active', item === button)); render(); })); search.addEventListener('input',render); sort.addEventListener('input',render); document.querySelector('[data-opportunity-reset]').addEventListener('click', () => { type='all';search.value='';sort.value='soon';document.querySelectorAll('[data-opportunity-type]').forEach((item)=>item.classList.toggle('active',item.dataset.opportunityType==='all'));render(); }); render();
})();
