(() => {
  const projects = [
    {title:'AI Attendance System', status:'Open', description:'A computer-vision attendance workflow designed around a practical classroom check-in.', skills:['Python','Machine Learning','React'], members:'2 / 4', owner:'Aarav', accent:'violet'},
    {title:'Campus Companion App', status:'Open', description:'One place to make student updates, locations, and everyday campus information easier to reach.', skills:['UI/UX','Flutter','Firebase'], members:'3 / 5', owner:'Nisha', accent:'mint'},
    {title:'Student Budget Planner', status:'In progress', description:'A simple financial planning tool that makes shared student expenses less stressful.', skills:['JavaScript','Design','Django'], members:'3 / 3', owner:'Rohan', accent:'peach'},
    {title:'Accessible Notes Reader', status:'Open', description:'A better reading layer for student material with focus, structure, and accessibility in mind.', skills:['HTML/CSS','JavaScript','Research'], members:'1 / 3', owner:'Priya', accent:'lime'},
    {title:'Lost & Found Map', status:'In progress', description:'A clear reporting and discovery map for items found around campus.', skills:['Maps','Python','UI/UX'], members:'4 / 4', owner:'Kunal', accent:'violet'},
    {title:'Open-source First Steps', status:'Open', description:'A friendly collaboration space for students making their first public contribution.', skills:['Git','Documentation','JavaScript'], members:'4 / 6', owner:'Meera', accent:'mint'}
  ];
  const grid=document.querySelector('[data-project-grid]'); const empty=document.querySelector('[data-project-empty]'); const count=document.querySelector('[data-project-count]'); const search=document.querySelector('[data-project-search]'); const modal=document.querySelector('[data-join-modal]'); let filter='all';
  const render=()=>{const term=search.value.toLowerCase();const list=projects.filter((p)=>(filter==='all'||p.status===filter)&&Object.values(p).join(' ').toLowerCase().includes(term));count.textContent=list.length;grid.hidden=!list.length;empty.hidden=Boolean(list.length);grid.innerHTML=list.map((p)=>`<article class="project-card"><div class="project-card-head"><span class="project-status ${p.status==='Open'?'open':'progress'}">${p.status}</span><span class="project-owner ${p.accent}">${p.owner.slice(0,1)}</span></div><div><h2>${p.title}</h2><p>${p.description}</p></div><div class="skill-list">${p.skills.map((s)=>`<span>${s}</span>`).join('')}</div><div class="project-card-foot"><span>◉ ${p.members} people</span>${p.status==='Open'?`<button data-join-project="${p.title}">Request to join →</button>`:'<span>Team full</span>'}</div></article>`).join('');};
  document.querySelectorAll('[data-project-filter]').forEach((button)=>button.addEventListener('click',()=>{filter=button.dataset.projectFilter;document.querySelectorAll('[data-project-filter]').forEach((item)=>item.classList.toggle('active',item===button));render();}));search.addEventListener('input',render);document.querySelector('[data-project-reset]').addEventListener('click',()=>{filter='all';search.value='';document.querySelectorAll('[data-project-filter]').forEach((item)=>item.classList.toggle('active',item.dataset.projectFilter==='all'));render();});grid.addEventListener('click',(event)=>{const button=event.target.closest('[data-join-project]');if(!button)return;document.querySelector('[data-join-copy]').textContent=`Your demo join request for “${button.dataset.joinProject}” isn’t sent anywhere. Django will provide this secure workflow.`;modal.hidden=false;});document.querySelector('[data-close-modal]').addEventListener('click',()=>modal.hidden=true);document.querySelector('[data-confirm-join]').addEventListener('click',()=>modal.hidden=true);render();
})();
